name: "Vault AppRole"

on:
  push:
    branches:
      - main
jobs:
  vault:
    name: "Import Secrets"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Vault Login using AppRole
        uses: hashicorp/vault-action@v2
        with:
            url: ${{ secrets.VAULT_ADDR }}
            method: approle
            namespace: admin
            roleId: ${{ secrets.VAULT_ROLE_ID }}
            secretId: ${{ secrets.VAULT_SECRET_ID }}
            path: kv
            secrets: network_devices/core_router01




